import pythoncom
import win32com.client

def main():
    try:
        pythoncom.CoInitialize()
        # Ensure we have the constants generated by using win32com.client.gencache.EnsureDispatch
        inv = win32com.client.gencache.EnsureDispatch("Inventor.Application")
        c = win32com.client.constants
        print(f"kPartDocumentObject = {getattr(c, 'kPartDocumentObject', 'N/A')}")
        print(f"kPlaneSurface = {getattr(c, 'kPlaneSurface', 'N/A')}")
        print(f"kLineSegmentCurve = {getattr(c, 'kLineSegmentCurve', 'N/A')}")
        print(f"kArbitraryViewOrientation = {getattr(c, 'kArbitraryViewOrientation', 'N/A')}")
        print(f"kDefaultViewOrientation = {getattr(c, 'kDefaultViewOrientation', 'N/A')}")
        print(f"kHiddenLineRemovedDrawingViewStyle = {getattr(c, 'kHiddenLineRemovedDrawingViewStyle', 'N/A')}")
    except Exception as e:
        print(f"Error: {e}")
    finally:
        pythoncom.CoUninitialize()

if __name__ == "__main__":
    main()
